[colors]
[colors.primary]
background = "#001e49"
foreground = "#eef1d7"

[colors.normal]
black   = "#001e49"
red     = "#c24e13"
green   = "#5a9f72"
yellow  = "#d2df6f"
blue    = "#1fb1a5"
magenta = "#4b64fd"
cyan    = "#83f0f1"
white   = "#CFD597"

[colors.bright]
black   = "#3f74c0"
red     = "#fba571"
green   = "#88c0a0"
yellow  = "#e1e1b3"
blue    = "#b3cbff"
magenta = "#8a8cff"
cyan    = "#d4fcfc"
white   = "#eef1d7"

[colors.cursor]
text   = "#001e49"
cursor = "#eef1d7"
